# Generated by Django 5.0.2 on 2024-02-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_rename_category_id_commercial_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
